name: Cross-platform Build

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Raylib (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo add-apt-repository ppa:game-dev/ppa -y
          sudo apt update
          sudo apt install -y libraylib-dev

      - name: Set up Raylib (Windows)
        if: runner.os == 'Windows'
        run: |
          mkdir raylib/include
          mkdir raylib/lib
          curl -LO https://github.com/raysan5/raylib/releases/download/5.0/raylib-5.0_win64_msvc16.zip
          powershell -Command "Expand-Archive -Path raylib-5.0_win64_msvc16.zip -DestinationPath ."
          cp raylib-5.0_win64_msvc16/include/raylib.h raylib/include/
          cp raylib-5.0_win64_msvc16/lib/raylib.lib raylib/lib/
          cp raylib-5.0_win64_msvc16/lib/raylib.dll raylib/lib/

      - name: Build
        run: make
