name: Cross-platform Build

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Linux: Build Raylib from source
      - name: Install Raylib on Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install -y gcc make libgl1-mesa-dev libx11-dev libxcursor-dev libxi-dev libxrandr-dev libxinerama-dev libxxf86vm-dev libopenal-dev
          git clone https://github.com/raysan5/raylib.git
          cd raylib/src
          make PLATFORM=PLATFORM_DESKTOP
          sudo make install

      # macOS: Use Homebrew
      - name: Install Raylib on macOS
        if: runner.os == 'macOS'
        run: |
          brew install raylib

      # Windows: Download Raylib binary
      - name: Set up Raylib on Windows
        if: runner.os == 'Windows'
        run: |
          curl -LO https://github.com/raysan5/raylib/releases/download/5.0/raylib-5.0_win64_msvc16.zip
          powershell -Command "Expand-Archive -Path raylib-5.0_win64_msvc16.zip -DestinationPath ."
          mkdir raylib
          mkdir raylib/include
          mkdir raylib/lib
          copy .\raylib-5.0_win64_msvc16\include\* .\raylib\include\
          copy .\raylib-5.0_win64_msvc16\lib\* .\raylib\lib\

      # Build
      - name: Build with Make
        run: make
