name: Cross-platform Build

on:
  push:
  pull_request:

jobs:
  build:
    timeout-minutes: 10
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Install Raylib on Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install -y build-essential cmake libgl1-mesa-dev libx11-dev libxcursor-dev libxi-dev libxrandr-dev libxinerama-dev libxxf86vm-dev libopenal-dev
          git clone https://github.com/raysan5/raylib.git
          mkdir raylib/build && cd raylib/build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          make -j$(nproc)
          sudo make install

      - name: Install Raylib on macOS
        if: runner.os == 'macOS'
        run: brew install raylib

      - name: Set up Raylib on Windows
        if: runner.os == 'Windows'
        run: |
          curl -LO https://github.com/raysan5/raylib/releases/download/5.0/raylib-5.0_win64_msvc16.zip
          powershell -Command "Expand-Archive -Path raylib-5.0_win64_msvc16.zip -DestinationPath ."
          mkdir raylib
          mkdir raylib/include
          mkdir raylib/lib
          copy .\raylib-5.0_win64_msvc16\include\* .\raylib\include\
          copy .\raylib-5.0_win64_msvc16\lib\* .\raylib\lib\

      - name: Build Project
        run: make
